ProcessorParserException: renamed to ArgProcessorParserException to simplify merge of "newagent" code. ArgProcessorParserException, SnippetParserException, ScopeParserException: subclass the ParserException class. Proc, ProcArgType, ProcMethod: renamed to ArgProcessor, ArgProcessorKind, and ArgProcessorMethod to simplify merge of "newagent" code.
Other classes updated to reflect the name changes.


git-svn-id: svn://svn.forge.objectweb.org/svnroot/disl/trunk@894 f1b219a8-1381-427d-9730-7f2851dc2a88