DiSLFatalException: added a constructor for formatted messages. ProcInstance: getApplyType()->getMode() which is consistent with the returned type. WeavingCode: reflect the changes prior to merge of new WeavingCode.
git-svn-id: svn://svn.forge.objectweb.org/svnroot/disl/trunk@809 f1b219a8-1381-427d-9730-7f2851dc2a88