DiSLException: added a constructor for formatted messages. DynamicContextException: renamed to InvalidContextUsageException to better fit its usage. DiSL, Weaver, WeavingCode: updated to reflect the change.
git-svn-id: svn://svn.forge.objectweb.org/svnroot/disl/trunk@805 f1b219a8-1381-427d-9730-7f2851dc2a88